"""Initial migration with all tables

Revision ID: 568c330c95c7
Revises: 
Create Date: 2026-02-27 17:22:32.033619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '568c330c95c7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agreements', sa.Column('inicontactdate', sa.Date(), nullable=True))
    op.add_column('agreements', sa.Column('date_of_order', sa.Date(), nullable=True))
    op.add_column('agreements', sa.Column('required_services', sa.Text(), nullable=True))
    op.add_column('agreements', sa.Column('freq_of_visit', sa.Text(), nullable=True))
    op.add_column('agreements', sa.Column('fees_description', sa.Text(), nullable=True))
    op.add_column('agreements', sa.Column('hazards', sa.Text(), nullable=True))
    op.add_column('agreements', sa.Column('perc_charged', sa.String(length=10), nullable=True))
    op.add_column('agreements', sa.Column('page1_cont_signature', sa.Text(), nullable=True))
    op.add_column('agreements', sa.Column('page3_1_signature', sa.Text(), nullable=True))
    op.alter_column('agreements', 'branch_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_foreign_key(None, 'agreements', 'tblbranch', ['branch_code'], ['branch_code'])
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'agreements', type_='foreignkey')
    op.alter_column('agreements', 'branch_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('agreements', 'page3_1_signature')
    op.drop_column('agreements', 'page1_cont_signature')
    op.drop_column('agreements', 'perc_charged')
    op.drop_column('agreements', 'hazards')
    op.drop_column('agreements', 'fees_description')
    op.drop_column('agreements', 'freq_of_visit')
    op.drop_column('agreements', 'required_services')
    op.drop_column('agreements', 'date_of_order')
    op.drop_column('agreements', 'inicontactdate')
    # ### end Alembic commands ###
