"""remove string length restrictions

Revision ID: d0914bb31fcc
Revises: 568c330c95c7
Create Date: 2026-03-07 12:05:32.577021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0914bb31fcc'
down_revision: Union[str, Sequence[str], None] = '568c330c95c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agreements', 'fees_description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agreements', sa.Column('fees_description', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
